name: share_localization
description: This plugin shares localization data across platforms.
version: 0.0.2
repository: https://github.com/EvGeniyLell/share_localization

publish_to: 'none'

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  meta: ^1.17.0
  path: ^1.9.1

dev_dependencies:
  lints: ^6.0.0
  mocktail: any
  test: ^1.27.0

executables:
  share_localization:

